"""
  Django settings for mysite project.
 -
  Generated by 'django-admin startproject' using Django 1.10.2.
 -
  For more information on this file, see
  https://docs.djangoproject.com/en/1.10/topics/settings/
 -
  For the full list of settings and their values, see
  https://docs.djangoproject.com/en/1.10/ref/settings/
  """
 @@ -20,7 +17,7 @@
  # See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/
  
  # SECURITY WARNING: keep the secret key used in production secret!
 -SECRET_KEY = 'syg27&%h0#jiy4tprl0oj*2uv^2tky$+84fm(k)euw^y&rnz-s'
 +SECRET_KEY = 'w7bjmfcr9)$dq2ixnioxl341aqrfvs4d=@ru#kduoo&chuq*e)'
  
  # SECURITY WARNING: don't run with debug turned on in production!
  DEBUG = True
 @@ -37,6 +34,9 @@
      'django.contrib.sessions',
      'django.contrib.messages',
      'django.contrib.staticfiles',
 +    'register',
 +    'Triangle',
 +    'catalog',
  ]
  
  MIDDLEWARE = [
 @@ -76,9 +76,9 @@
  DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.mysql',
 -        'NAME': 'mysite',
 -        'USER': 'root',
 -        'PASSWORD': '153759',
 +        'NAME': 'GithubTriangle',
 +        'USER': 'Github',
 +        'PASSWORD': 'password',
          'HOST': 'localhost',
          'PORT': '3306',
      }
 @@ -121,4 +121,19 @@
  # Static files (CSS, JavaScript, Images)
  # https://docs.djangoproject.com/en/1.10/howto/static-files/
  
 +
  STATIC_URL = '/static/'
 +
 +STATICFILES_DIRS = [
 +    #normpath(join(SITE_ROOT, 'static')),
 +    os.path.join(BASE_DIR, "static"),
 +    #'/Users/booranasit/Desktop/Django/Pokemon/mysite/asset',
 +]
 +
 +STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn")
 +
 +
 +
 +
 +
 +