# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustID', models.IntegerField(max_length=11)),
                ('Pid', models.CharField(max_length=200)),
                ('Pprice', models.FloatField()),
                ('Pamount', models.FloatField()),
            ],
        ),
    ]
