# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('dateofbirth', models.CharField(max_length=45)),
                ('phonenum', models.CharField(max_length=45)),
            ],
        ),
    ]
