# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData3',
        ),
    ]
