# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
